# Generated by Django 4.1.5 on 2023-01-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_comment2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment2',
            name='product',
            field=models.IntegerField(verbose_name='상품'),
        ),
    ]
