# Generated by Django 4.1.5 on 2023-01-19 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_comment2_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment2',
        ),
    ]
